<a href="https://colab.research.google.com/github/Ravikumar10593-hub/python_conepts/blob/main/Practising_python_class_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#create a empty class
class Myclass:
  pass


In [5]:
#init function 
class Myclass:
  def __init__(self,x):
    self.x=x
#Object creation of the class    
obj = Myclass(5)
#printing the value by object_name.variable_name
print(obj.x)


5


# Way to create a simple class to take and print the details.

1.   Create a class.
2.   Create a init variable.
3.   Create a display varible with argument self.
4.   Create class object
5.   object.func_name()



In [7]:
#creation of some funtions
class Myclass:
  def __init__(self,name,roll,standard):
    self.n=name
    self.r=roll
    self.s=standard

#we read the three variable and now it is time to print all three
#value using another function called display

  def display(self):
    print('My Name is:',self.n)
    print('My roll number is:',self.r)
    print('My class is:',self.s,'th')

obj=Myclass("Ravi",10593,12) 
obj.display()

My Name is: Ravi
My roll number is: 10593
My class is: 12 th


In [8]:
#If i want to change the roll from 10593 to 10553
obj.r=10553

In [9]:
obj.display()

My Name is: Ravi
My roll number is: 10553
My class is: 12 th


**As we can see that now roll hass succesfully being changed from 10593 to 10553**